"use strict";
const assert=require("node:assert/strict");
const {boot,source}=require("./video_global_speed_harness.cjs");
assert.match(source,/@version\s+0\.5\.0/);
assert.doesNotMatch(source,/(?:media|video)\.playbackRate\s*=/);
assert.doesNotMatch(source,/defaultPlaybackRate\s*=/);
const x=boot();
assert.equal(x.heartbeat.version,5);
assert.equal(x.heartbeat.playing,true);
assert.equal(x.heartbeat.browser,"firefox");
assert.equal(x.heartbeat.focused,false);
x.fire(35);
assert.equal(x.keyEvents.length,2,"send only keydown and keyup into GS");
assert.equal(x.keyEvents[0].code,"KeyA");
assert.equal(x.keyEvents[0].type,"keydown");
assert.equal(x.keyEvents[1].type,"keyup");
assert.equal(x.playbackRate,1.4);
assert.equal(x.writes,1,"only mock Global Speed changed media rate");
x.fire(750);
assert.equal(x.reports.length,1);
assert.equal(x.reports[0].ok,true);
assert.equal(x.reports[0].engine,"global-speed");
assert.equal(x.reports[0].key,"KeyA");
assert.equal(x.reports[0].pip,true);
console.log("GLOBAL_SPEED_KEY_FORWARDING_TEST_PASSED 1.5x=>1.4x via GS");
