"use strict";
const assert=require("node:assert/strict");
const {boot}=require("./video_global_speed_harness.cjs");
const inactive=boot({engineEnabled:false});
inactive.fire(35);
assert.equal(inactive.playbackRate,1.5);
assert.equal(inactive.writes,0,"helper never directly controls video");
inactive.fire(750);
assert.equal(inactive.reports[0].ok,false);
assert.equal(inactive.reports[0].reason,"global-speed-not-observed");
const normal=boot({pip:false});
normal.fire(35);
assert.equal(normal.keyEvents.length,0);
assert.equal(normal.playbackRate,1.5);
const wrongClient=boot({eventTargetMatches:false});
wrongClient.fire(35);
assert.equal(wrongClient.keyEvents.length,0);
const textInput=boot({sourceInputFocused:true});
textInput.fire(35);
assert.equal(textInput.keyEvents.length,0);
assert.equal(textInput.playbackRate,1.5);
assert.equal(textInput.reports[0].reason,"source-text-input-focused");
console.log("GLOBAL_SPEED_PIP_ISOLATION_TEST_PASSED no fallback/ordinary/other client/input");
